# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - news-front

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write   # OIDC 토큰 발급
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'news-front'
          slot-name: 'Production'
          package: './frontend'
          # Azure App Service의 빌드 엔진(Oryx)이 package.json을 보고
          # 자동으로 npm install과 npm run build를 실행하도록 설정합니다.