name: Build and Deploy Next.js to Azure

on:
  push:
    branches: test
  pull_request:
    branches: test

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build Next.js application
      run: npm run build
      
    # 빌드 결과물 확인 (디버깅용)
    - name: List build files
      run: |
        ls -la
        ls -la .next/
        
    # standalone 빌드인 경우 추가
    - name: Copy standalone files (if using standalone)
      run: |
        if [ -d ".next/standalone" ]; then
          cp -r .next/standalone/* ./
          cp -r public .next/standalone/
          cp -r .next/static .next/standalone/.next/
        fi
    
    # v4 사용하여 아티팩트 업로드
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build
        path: |
          .next/
          public/
          package.json
          package-lock.json
          next.config.js
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: nextjs-build
        path: ./
    
    # 배포용 압축 파일 생성
    - name: Create deployment package
      run: |
        # .next 폴더가 포함되도록 압축
        zip -r frontend_artifact.zip . -x "*.git*" "node_modules/*"
        ls -la *.zip
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './frontend_artifact.zip'  # .tar.gz 대신 .zip 사용